%% Import data from text file.
% Script for importing data from the following text file:
%
%    D:\Dateien\HS München\IG1\Computational Geometry - Fischer\CGeo\Aufgabe4\qhull-2015.2\bin\final.dat
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/06/10 00:13:41

%% Initialize variables.
filename = 'D:\Dateien\HS München\IG1\Computational Geometry - Fischer\CGeo\Aufgabe4\final.dat';
delimiter = ' ';

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string',  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
X = dataArray{:, 1};
Y = dataArray{:, 2};
Z = dataArray{:, 3};


%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;

%%%%My Code%%%%
%Z(find(Z==0))=1.0e-5;%max(Z)+100; %%adjust the false values to the highest
%Z(find(Z==-1))=0;%max(Z)+100; %%adjust the false values to the highest
figure(4)
[xq,yq] = meshgrid(linspace(min(X),max(X),size(X,1)), linspace(min(Y),max(Y),size(Y,1)));
zq = griddata(X,Y,Z,xq,yq);
%abc=min(zq);
%abc(find(abc<1e-5))=1000;
%zq(find(zq<1e-5))=1e-5;%min(abc');%max(Z)+100; %%adjust the false values to the highest

mesh(xq,yq,zq)
hold on
a = plot3(X,Y,Z, 'o')
set(a,'MarkerEdgeColor','r','MarkerFaceColor','r')
set(gca,'zscale','log');
set(gca,'xscale','log');
set(gca,'XLim', [100 max(X)] );
set(gca,'ZLim', [1e-05 max(Z)] );

title('Time for qhull with different dimensions and points')
xlabel('Quantitiy of random points')
ylabel('Dimensions')
zlabel('Time in s')